server:
  port: 8090
auth:
  rules:
    disabled: false
    identityUrlRoot: "http://localhost:8090"
    identityUrlPath: "/usersgroups-query-api/query/api/rest/usersgroups/users/logged-in-user/permissions"
    excludePathPrefixes: "/usersgroups-query-api/,/actuator,/error"
    actionRequired: true
    userIdHeaderName: "CJSCPPUID"
    actionHeaderName: "CPP-ACTION"
    acceptHeader: "application/vnd.usersgroups.get-logged-in-user-permissions+json"

  drools:
    reloadOnEachRequest: true
    droolsClasspathPattern: classpath:/drools-test/**/*.drl
